<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEQnEVwh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEQnEVwh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEQnEVwh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEQnEVwh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEQnEVwh\App_KernelDevDebugContainer([
    'container.build_hash' => 'EQnEVwh',
    'container.build_id' => '8e8dbe10',
    'container.build_time' => 1609348254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEQnEVwh');
